package com.efrei.pokemon_tcg.constants;

public enum TypeAttackCombo {
    BLAST_STRIKE, SHADOW_FRENZY, THUNDER_TORNADO, VOLCANIC_ERUPTION, PSYCHO_BARRAGE, FROSTBITE_FURY, DRAGON_COMET, METEOR_CRUSH, PHANTOM_RAMPAGE, CHAOS_QUAKE
}
